export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const POSTS_FETCHED = "POSTS_FETCHED";
export const POST_CREATED = "POST_CREATED";
export const POST_EDITED = "POST_EDITED";
export const POST_DELETED = "POST_DELETED";